config/routes.rb
DripDispatch::Application.routes.draw do
  
  match '/run_drips/runDrip', :controller => 'run_drips', :action => 'runDrip'
  
  match '/customers/demo', :controller => 'customers', :action => 'demo'
  
  resources :dispatched_drips
  
  resources :run_drips

  resources :customers

  resources :drip_emails

  resources :dispatched_emails

  resources :drips

  resources :emails
  
  

end

app/models/dispatched_email.rb
class DispatchedEmail < ActiveRecord::Base
  attr_accessible :dispatched_drip_id, :email_id, :sent_date
  
  belongs_to :dispatched_drip
  belongs_to :email
  
  def send_email
    DripMailer.send_email(self).deliver
  end
  
end

app/controllers/dispatched_emails_controller.rb
class DispatchedEmailsController < ApplicationController
  # GET /dispatched_emails
  # GET /dispatched_emails.json
  def index
    @dispatched_emails = DispatchedEmail.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dispatched_emails }
    end
  end

  # GET /dispatched_emails/1
  # GET /dispatched_emails/1.json
  def show
    @dispatched_email = DispatchedEmail.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dispatched_email }
    end
  end

  # GET /dispatched_emails/new
  # GET /dispatched_emails/new.json
  def new
    @dispatched_email = DispatchedEmail.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dispatched_email }
    end
  end

  # GET /dispatched_emails/1/edit
  def edit
    @dispatched_email = DispatchedEmail.find(params[:id])
  end

  # POST /dispatched_emails
  # POST /dispatched_emails.json
  def create
    @dispatched_email = DispatchedEmail.new(params[:dispatched_email])

    respond_to do |format|
      if @dispatched_email.save
        format.html { redirect_to @dispatched_email, notice: 'Dispatched email was successfully created.' }
        format.json { render json: @dispatched_email, status: :created, location: @dispatched_email }
      else
        format.html { render action: "new" }
        format.json { render json: @dispatched_email.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dispatched_emails/1
  # PUT /dispatched_emails/1.json
  def update
    @dispatched_email = DispatchedEmail.find(params[:id])

    respond_to do |format|
      if @dispatched_email.update_attributes(params[:dispatched_email])
        format.html { redirect_to @dispatched_email, notice: 'Dispatched email was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dispatched_email.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dispatched_emails/1
  # DELETE /dispatched_emails/1.json
  def destroy
    @dispatched_email = DispatchedEmail.find(params[:id])
    @dispatched_email.destroy

    respond_to do |format|
      format.html { redirect_to dispatched_emails_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/dispatched_emails_helper.rb
module DispatchedEmailsHelper
end

app/views/dispatched_emails/_form.html.erb
<%= form_for(@dispatched_email) do |f| %>
  <% if @dispatched_email.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dispatched_email.errors.count, "error") %> prohibited this dispatched_email from being saved:</h2>

      <ul>
      <% @dispatched_email.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.label :sent_date %><br />
    <%= f.date_select :sent_date %>
  </div>
  <div class="field">
    <%= f.label :email_id %><br />
    <%= f.number_field :email_id %>
  </div>
  <div class="field">
    <%= f.label :dispatched_drip_id %><br />
    <%= f.number_field :dispatched_drip_id %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dispatched_emails/edit.html.erb
<h1>Editing dispatched_email</h1>

<%= render 'form' %>

<%= link_to 'Show', @dispatched_email %> |
<%= link_to 'Back', dispatched_emails_path %>

app/views/dispatched_emails/index.html.erb
<h1>Listing dispatched_emails</h1>

<table>
  <tr>
    
    <th>Sent date</th>
    <th>Email</th>
    <th>Dispatched Drip</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dispatched_emails.each do |dispatched_email| %>
  <tr>
    
    <td><%= dispatched_email.sent_date %></td>
    <td><%= dispatched_email.email_id %></td>
    <td><%= dispatched_email.dispatched_drip_id %></td>
    <td><%= link_to 'Show', dispatched_email %></td>
    <td><%= link_to 'Edit', edit_dispatched_email_path(dispatched_email) %></td>
    <td><%= link_to 'Destroy', dispatched_email, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dispatched email', new_dispatched_email_path %>

app/views/dispatched_emails/new.html.erb
<h1>New dispatched_email</h1>

<%= render 'form' %>

<%= link_to 'Back', dispatched_emails_path %>

app/views/dispatched_emails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Dispatched Drip ID:</b>
  <%= @dispatched_email.dispatched_drip_id %>
</p>

<p>
  <b>Sent date:</b>
  <%= @dispatched_email.sent_date %>
</p>

<p>
  <b>Email:</b>
  <%= @dispatched_email.email_id %>
</p>


<%= link_to 'Edit', edit_dispatched_email_path(@dispatched_email) %> |
<%= link_to 'Back', dispatched_emails_path %>