config/routes.rb
DripDispatch::Application.routes.draw do
  
  match '/run_drips/runDrip', :controller => 'run_drips', :action => 'runDrip'
  
  match '/customers/demo', :controller => 'customers', :action => 'demo'
  
  resources :dispatched_drips
  
  resources :run_drips

  resources :customers

  resources :drip_emails

  resources :dispatched_emails

  resources :drips

  resources :emails
  
  

end

app/models/dispatched_drip.rb
class DispatchedDrip < ActiveRecord::Base
  attr_accessible :customer_id, :drip_id
  belongs_to :customer
  
  has_many :dispatched_emails
  after_create :send_first_email
  
  
  def send_first_email
    dispatched_email = dispatched_emails.build(sent_date: Date.today, email_id: Email.find(:all, :conditions => ['drip_id = ? AND sequence = ?',drip_id,1]).first.id)
    dispatched_email.save
    dispatched_email.send_email
  end
  
  def send_next_email(next_dispatch_id)
    dispatched_email = dispatched_emails.build(sent_date: Date.today, email_id: next_dispatch_id)
    dispatched_email.save
    dispatched_email.send_email
  end
  
end

app/controllers/dispatched_drips_controller.rb
class DispatchedDripsController < ApplicationController
  # GET /dispatched_drips
  # GET /dispatched_drips.json
  def index
    @dispatched_drips = DispatchedDrip.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dispatched_drips }
    end
  end

  # GET /dispatched_drips/1
  # GET /dispatched_drips/1.json
  def show
    @dispatched_drip = DispatchedDrip.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dispatched_drip }
    end
  end

  # GET /dispatched_drips/new
  # GET /dispatched_drips/new.json
  def new
    @dispatched_drip = DispatchedDrip.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dispatched_drip }
    end
  end

  # GET /dispatched_drips/1/edit
  def edit
    @dispatched_drip = DispatchedDrip.find(params[:id])
  end

  # POST /dispatched_drips
  # POST /dispatched_drips.json
  def create
    @dispatched_drip = DispatchedDrip.new(params[:dispatched_drip])

    respond_to do |format|
      if @dispatched_drip.save
        format.html { redirect_to @dispatched_drip, notice: 'Dispatched drip was successfully created.' }
        format.json { render json: @dispatched_drip, status: :created, location: @dispatched_drip }
      else
        format.html { render action: "new" }
        format.json { render json: @dispatched_drip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dispatched_drips/1
  # PUT /dispatched_drips/1.json
  def update
    @dispatched_drip = DispatchedDrip.find(params[:id])

    respond_to do |format|
      if @dispatched_drip.update_attributes(params[:dispatched_drip])
        format.html { redirect_to @dispatched_drip, notice: 'Dispatched drip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dispatched_drip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dispatched_drips/1
  # DELETE /dispatched_drips/1.json
  def destroy
    @dispatched_drip = DispatchedDrip.find(params[:id])
    @dispatched_drip.destroy

    respond_to do |format|
      format.html { redirect_to dispatched_drips_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/dispatched_drips_helper.rb
module DispatchedDripsHelper
end

app/views/dispatched_drips/_form.html.erb
<%= form_for(@dispatched_drip) do |f| %>
  <% if @dispatched_drip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dispatched_drip.errors.count, "error") %> prohibited this dispatched_drip from being saved:</h2>

      <ul>
      <% @dispatched_drip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customer_id %><br />
    <%= f.number_field :customer_id %>
  </div>
  <div class="field">
    <%= f.label :drip_id %><br />
    <%= f.number_field :drip_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dispatched_drips/edit.html.erb
<h1>Editing dispatched_drip</h1>

<%= render 'form' %>

<%= link_to 'Show', @dispatched_drip %> |
<%= link_to 'Back', dispatched_drips_path %>

app/views/dispatched_drips/index.html.erb
<h1>Listing dispatched_drips</h1>

<table>
  <tr>
    <th>Customer</th>
    <th>Drip</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dispatched_drips.each do |dispatched_drip| %>
  <tr>
    <td><%= dispatched_drip.customer_id %></td>
    <td><%= dispatched_drip.drip_id %></td>
    <td><%= link_to 'Show', dispatched_drip %></td>
    <td><%= link_to 'Edit', edit_dispatched_drip_path(dispatched_drip) %></td>
    <td><%= link_to 'Destroy', dispatched_drip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dispatched drip', new_dispatched_drip_path %>

app/views/dispatched_drips/new.html.erb
<h1>New dispatched_drip</h1>

<%= render 'form' %>

<%= link_to 'Back', dispatched_drips_path %>

app/views/dispatched_drips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Customer:</b>
  <%= @dispatched_drip.customer_id %>
</p>

<p>
  <b>Drip:</b>
  <%= @dispatched_drip.drip_id %>
</p>


<%= link_to 'Edit', edit_dispatched_drip_path(@dispatched_drip) %> |
<%= link_to 'Back', dispatched_drips_path %>