config/routes.rb
DripDispatch::Application.routes.draw do
  
  match '/run_drips/runDrip', :controller => 'run_drips', :action => 'runDrip'
  
  match '/customers/demo', :controller => 'customers', :action => 'demo'
  
  resources :dispatched_drips
  
  resources :run_drips

  resources :customers

  resources :drip_emails

  resources :dispatched_emails

  resources :drips

  resources :emails
  
  

end

app/models/drip.rb
class Drip < ActiveRecord::Base
  attr_accessible :name
  has_many :emails
end

app/controllers/drips_controller.rb
class DripsController < ApplicationController
  # GET /drips
  # GET /drips.json
  def index
    @drips = Drip.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @drips }
    end
  end

  # GET /drips/1
  # GET /drips/1.json
  def show
    @drip = Drip.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @drip }
    end
  end

  # GET /drips/new
  # GET /drips/new.json
  def new
    @drip = Drip.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @drip }
    end
  end

  # GET /drips/1/edit
  def edit
    @drip = Drip.find(params[:id])
  end

  # POST /drips
  # POST /drips.json
  def create
    @drip = Drip.new(params[:drip])

    respond_to do |format|
      if @drip.save
        format.html { redirect_to @drip, notice: 'Drip was successfully created.' }
        format.json { render json: @drip, status: :created, location: @drip }
      else
        format.html { render action: "new" }
        format.json { render json: @drip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /drips/1
  # PUT /drips/1.json
  def update
    @drip = Drip.find(params[:id])

    respond_to do |format|
      if @drip.update_attributes(params[:drip])
        format.html { redirect_to @drip, notice: 'Drip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @drip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drips/1
  # DELETE /drips/1.json
  def destroy
    @drip = Drip.find(params[:id])
    @drip.destroy

    respond_to do |format|
      format.html { redirect_to drips_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/drips_helper.rb
module DripsHelper
end

app/views/drips/_form.html.erb
<%= form_for(@drip) do |f| %>
  <% if @drip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@drip.errors.count, "error") %> prohibited this drip from being saved:</h2>

      <ul>
      <% @drip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/drips/edit.html.erb
<h1>Editing drip</h1>

<%= render 'form' %>

<%= link_to 'Show', @drip %> |
<%= link_to 'Back', drips_path %>

app/views/drips/index.html.erb
<h1>Listing drips</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @drips.each do |drip| %>
  <tr>
    <td><%= drip.name %></td>
    <td><%= link_to 'Show', drip %></td>
    <td><%= link_to 'Edit', edit_drip_path(drip) %></td>
    <td><%= link_to 'Destroy', drip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Drip', new_drip_path %>

app/views/drips/new.html.erb
<h1>New drip</h1>

<%= render 'form' %>

<%= link_to 'Back', drips_path %>

app/views/drips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @drip.name %>
</p>


<%= link_to 'Edit', edit_drip_path(@drip) %> |
<%= link_to 'Back', drips_path %>